function generateReport() {

    const report = `

CYBERINTEL AI
DIGITAL FORENSIC INCIDENT REPORT

========================================

Incident ID:
INC-2026-00942

Classification:
Credential Phishing

Risk Score:
91/100

Risk Level:
HIGH RISK

Status:
Under Investigation

First Detected:
12 Sep 2026, 09:41

========================================

NETWORK INTELLIGENCE

IP Address:
203.0.113.42

Approximate Location:
Example Region

Network:
Example ISP

Geolocation Confidence:
Medium

NOTE:
IP geolocation is approximate and should
not be interpreted as the attacker's exact
physical location.

========================================

FORENSIC TIMELINE

09:41:02
Suspicious email received.

09:41:03
Email header information extracted.

09:41:04
Suspicious URL identified.

09:41:05
AI threat classification completed.

09:41:07
Automated response recommended:
QUARANTINE

========================================

INDICATORS OF COMPROMISE

Email:
suspicious-sender@example.test

IP:
203.0.113.42

URL:
suspicious.example.test/login

Keywords:
urgent / verify / password

========================================

RECOMMENDED ACTION

Quarantine the suspicious email,
investigate extracted indicators,
and notify the security administrator.

========================================

Generated by CyberIntel AI
AI-Powered Email Threat Detection
and Forensic Intelligence Platform

`;

    const blob =
        new Blob(
            [report],
            {
                type: "text/plain"
            }
        );


    const url =
        URL.createObjectURL(blob);


    const link =
        document.createElement("a");


    link.href = url;

    link.download =
        "CyberIntel_Forensic_Report.txt";


    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);


    URL.revokeObjectURL(url);

}
